# Generated by Django 5.2.7 on 2025-10-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app_product.product')),
            ],
            options={
                'verbose_name': 'Current Stock',
                'verbose_name_plural': 'Current Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Purchase/Sale/Return reference', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='app_product.product')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock Histories',
                'ordering': ('-created_at',),
            },
        ),
    ]
