# Generated by Django 5.2.7 on 2025-10-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sales', '0002_alter_salesinvoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='paid_amount',
            new_name='received_amount',
        ),
    ]
